#!/bin/bash
# SessionStart hook: put a maid "on shift".
# Reads the chosen persona's body (frontmatter stripped) from the plugin's own
# bundled `vendor/` dir (generated by build.ts from @claudecafe/maids) — self-
# contained, so it works from the marketplace cache with no external link, no env
# var, no repo path, and no `node` dependency (hooks run in a non-interactive
# shell that may not have node/bun on PATH).
# Shift order: CLAUDE_MAID env (one-shot override) > this session's own shift file
# > ~/.claude/maid-on-shift (both written by /maid) > claudia. The per-session layer
# is what lets two windows run different maids at once. "none" = nobody on shift (no
# persona injected — for users who bring their own persona via CLAUDE.md).
set -euo pipefail
PAYLOAD="$(cat)"   # the hook payload carries session_id

SESSION_ID="$(printf '%s' "$PAYLOAD" |
  sed -n 's/.*"session_id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)"

# 缺檔是正常情況（那一層沒排班），不能讓 set -e 把整支 hook 掐掉
read_shift() { [ -f "$1" ] && tr -d '[:space:]' < "$1"; return 0; }

MAID="${CLAUDE_MAID:-}"
[ -n "$MAID" ] || [ -z "$SESSION_ID" ] ||
  MAID="$(read_shift "$HOME/.claude/maid-state/$SESSION_ID/on-shift")"
[ -n "$MAID" ] || MAID="$(read_shift "$HOME/.claude/maid-on-shift")"
MAID="${MAID:-claudia}"
[ "$MAID" = "none" ] && exit 0   # nobody on shift -> stay in the default voice
CAST_DIR="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}/vendor"
FILE="$CAST_DIR/$MAID.md"

[ -f "$FILE" ] || exit 0   # persona not found -> stay in the default voice

echo "Adopt this persona for the entire session — it overrides the default assistant voice:"
echo
# Emit the body, stripping the leading YAML frontmatter (--- ... ---).
awk 'NR==1 && $0=="---"{f=1; next} f && $0=="---"{f=0; next} !f' "$FILE"
echo
echo "Respond in 台灣中文."
