#!/bin/bash
# SessionStart hook: put a maid "on shift".
# Reads the chosen persona's body (frontmatter stripped) from the plugin's own
# bundled `vendor/` dir (generated by build.ts from @claudecafe/maids) — self-
# contained, so it works from the marketplace cache with no external link, no env
# var, no repo path, and no `node` dependency (hooks run in a non-interactive
# shell that may not have node/bun on PATH).
# Shift order: CLAUDE_MAID env (one-shot override) > ~/.claude/maid-on-shift
# (written by the /maid command) > claudia. "none" = nobody on shift (no persona
# injected — for users who bring their own persona via CLAUDE.md).
set -euo pipefail
cat > /dev/null   # drain the hook payload on stdin

STATE_FILE="$HOME/.claude/maid-on-shift"
MAID="${CLAUDE_MAID:-}"
if [ -z "$MAID" ] && [ -f "$STATE_FILE" ]; then
  MAID="$(tr -d '[:space:]' < "$STATE_FILE")"
fi
MAID="${MAID:-claudia}"
[ "$MAID" = "none" ] && exit 0   # nobody on shift -> stay in the default voice
CAST_DIR="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}/vendor"
FILE="$CAST_DIR/$MAID.md"

[ -f "$FILE" ] || exit 0   # persona not found -> stay in the default voice

echo "Adopt this persona for the entire session — it overrides the default assistant voice:"
echo
# Emit the body, stripping the leading YAML frontmatter (--- ... ---).
awk 'NR==1 && $0=="---"{f=1; next} f && $0=="---"{f=0; next} !f' "$FILE"
echo
echo "Respond in 台灣中文."
