// @vitest-environment jsdom
import { act, renderHook } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import { useSpeech } from './useSpeech'

describe('useSpeech', () => {
  it('shows complete lines immediately', () => {
    const onShow = vi.fn()
    const onDone = vi.fn()
    const { result } = renderHook(() => useSpeech())
    act(() => result.current.say('hello there', { onShow, onDone }))
    expect(result.current.line).toBe('hello there')
    expect(result.current.isDone).toBe(true)
    expect(onShow).toHaveBeenCalledOnce()
    expect(onDone).toHaveBeenCalledOnce()
  })

  it('restores transcript pages at the latest without replaying hooks and appends across turns', () => {
    const onShow = vi.fn()
    const { result } = renderHook(() => useSpeech())
    act(() => result.current.restore(['one', 'two', 'three', 'four', 'five']))
    expect(result.current.pageIndex).toBe(5)
    expect(result.current.pageCount).toBe(5)
    expect(result.current.line).toBe('five')
    expect(result.current.canPrevious).toBe(true)
    act(() => result.current.previous())
    expect(result.current.pageIndex).toBe(4)
    act(() => result.current.restore(['one', 'two', 'three', 'four', 'five']))
    act(() => { result.current.beginTurn(); result.current.stream('new', 'six', true, { onShow }) })
    expect(result.current.pageCount).toBe(6)
    expect(result.current.pageIndex).toBe(6)
    expect(result.current.line).toBe('six')
    expect(onShow).toHaveBeenCalledOnce()
    act(() => result.current.restore([]))
    expect(result.current.pageCount).toBe(0)
  })

  it('keeps the reader on an older reply when a new turn starts', () => {
    const { result } = renderHook(() => useSpeech())
    act(() => result.current.restore(['first', 'second']))
    act(() => result.current.previous())
    act(() => { result.current.beginTurn(); result.current.stream('third', 'third reply', true) })
    expect(result.current.line).toBe('first')
    expect(result.current.pageCount).toBe(3)
    expect(result.current.pageIndex).toBe(1)
  })

  it('reads a queued new reply directly from older history and runs its show hook once', () => {
    const onShow = vi.fn()
    const { result } = renderHook(() => useSpeech())
    act(() => result.current.restore(['first', 'second', 'third']))
    act(() => result.current.previous())
    act(() => { result.current.beginTurn(); result.current.stream('new', 'new reply', true, { onShow }) })
    expect(result.current.line).toBe('second')
    expect(result.current.canReadNext).toBe(true)
    act(() => result.current.readNext())
    expect(result.current.line).toBe('new reply')
    expect(result.current.pageIndex).toBe(4)
    expect(onShow).toHaveBeenCalledOnce()
    expect(result.current.canReadNext).toBe(false)
  })

  it('replaces only the synthetic opening when the first turn begins', () => {
    const { result } = renderHook(() => useSpeech())
    act(() => result.current.say('opening'))
    act(() => result.current.beginTurn(true))
    expect(result.current.pageCount).toBe(0)
    act(() => result.current.stream('reply', 'reply', true))
    expect(result.current.pageCount).toBe(1)
    expect(result.current.pageIndex).toBe(1)
  })

  it('keeps seen pages for previous and next without replaying hooks or acts', () => {
    const show1 = vi.fn()
    const show2 = vi.fn()
    const done2 = vi.fn()
    const play = vi.fn()
    const { result } = renderHook(() => useSpeech())
    act(() => result.current.say('one', { onShow: show1 }))
    act(() => { result.current.act(play); result.current.say('two', { onShow: show2, onDone: done2 }) })
    expect(result.current.queued).toBe(1)
    act(() => result.current.advance())
    expect(result.current.line).toBe('two')
    expect(result.current.pageCount).toBe(2)
    expect(play).toHaveBeenCalledOnce()
    act(() => result.current.previous())
    expect(result.current.line).toBe('one')
    expect(result.current.canNext).toBe(true)
    act(() => result.current.advance())
    expect(result.current.line).toBe('two')
    expect(show1).toHaveBeenCalledOnce()
    expect(show2).toHaveBeenCalledOnce()
    expect(done2).toHaveBeenCalledOnce()
    expect(play).toHaveBeenCalledOnce()
  })

  it('updates a stored stream page while it is offscreen without moving the reader', () => {
    const { result } = renderHook(() => useSpeech())
    act(() => result.current.stream('live', 'part', false))
    act(() => result.current.say('later'))
    act(() => result.current.stream('live', 'complete text', true))
    act(() => result.current.advance())
    act(() => result.current.stream('live', 'complete text', true))
    expect(result.current.line).toBe('later')
    expect(result.current.pageCount).toBe(2)
    act(() => result.current.previous())
    expect(result.current.line).toBe('complete text')
    expect(result.current.isDone).toBe(true)
  })

  it('clear preserves the visible text as past while discarding turn pages and queued questions', () => {
    const onDrop = vi.fn()
    const { result } = renderHook(() => useSpeech())
    act(() => result.current.say('visible'))
    act(() => result.current.say('question', { onDrop }))
    act(() => result.current.clear())
    expect(result.current.line).toBe('visible')
    expect(result.current.past).toBe(true)
    expect(result.current.pageCount).toBe(0)
    expect(result.current.pageIndex).toBe(0)
    expect(onDrop).toHaveBeenCalledOnce()
  })

  it('cut replaces the page history, drops queued hooks and ignores discarded stream snapshots', () => {
    const onDrop = vi.fn()
    const { result } = renderHook(() => useSpeech())
    act(() => result.current.stream('old', 'partial', false))
    act(() => result.current.say('permission', { onDrop }))
    act(() => result.current.cut('replacement'))
    act(() => result.current.stream('old', 'resurrected', true))
    expect(result.current.line).toBe('replacement')
    expect(result.current.pageCount).toBe(1)
    expect(result.current.queued).toBe(0)
    expect(onDrop).toHaveBeenCalledOnce()
  })

  it('retains queued permissions until advancing and runs queued acts in order once', () => {
    const onShow = vi.fn(); const play = vi.fn()
    const { result } = renderHook(() => useSpeech())
    act(() => result.current.say('first'))
    act(() => { result.current.act(play); result.current.say('permission', { halt: true, onShow }) })
    expect(result.current.queued).toBe(1)
    expect(result.current.pageCount).toBe(2)
    expect(onShow).not.toHaveBeenCalled()
    act(() => result.current.advance())
    expect(play).toHaveBeenCalledOnce()
    expect(onShow).toHaveBeenCalledOnce()
    expect(result.current.line).toBe('permission')
  })

  it('counts queued pages and enables next when the active stream completes', () => {
    const { result } = renderHook(() => useSpeech())
    act(() => result.current.stream('active', 'partial', false))
    act(() => result.current.say('waiting'))
    expect(result.current.pageCount).toBe(2)
    expect(result.current.canNext).toBe(false)
    act(() => result.current.stream('active', 'complete', true))
    expect(result.current.canNext).toBe(true)
    act(() => result.current.advance())
    expect(result.current.line).toBe('waiting')
    expect(result.current.pageCount).toBe(2)
  })

  it('continues accepting snapshots for a previously visited stream', () => {
    const { result } = renderHook(() => useSpeech())
    act(() => result.current.stream('first', 'first complete', true))
    act(() => result.current.say('second'))
    act(() => result.current.advance())
    act(() => result.current.stream('first', 'updated first', true))
    expect(result.current.line).toBe('second')
    act(() => result.current.previous())
    expect(result.current.line).toBe('updated first')
  })

  it('keeps acts between queued pages in order', () => {
    const play = vi.fn()
    const { result } = renderHook(() => useSpeech())
    act(() => result.current.stream('live', 'partial', false))
    act(() => result.current.act(play))
    act(() => result.current.say('later'))
    act(() => result.current.stream('live', 'complete', true))
    expect(play).not.toHaveBeenCalled()
    act(() => result.current.advance())
    expect(result.current.line).toBe('later')
    expect(play).toHaveBeenCalledOnce()
  })

  it('drains acts behind an already-complete queued page when that page is opened', () => {
    const play = vi.fn()
    const { result } = renderHook(() => useSpeech())
    act(() => {
      result.current.say('first')
      result.current.stream('second', 'complete', true)
      result.current.act(play)
    })
    expect(play).not.toHaveBeenCalled()
    act(() => result.current.advance())
    expect(play).toHaveBeenCalledOnce()
    act(() => result.current.previous())
    act(() => result.current.advance())
    expect(play).toHaveBeenCalledOnce()
  })

  it.each(['clear', 'cut', 'restore'] as const)('%s invalidates stream pages even when they are offscreen', (operation) => {
    const { result } = renderHook(() => useSpeech())
    act(() => result.current.stream('first', 'first complete', true))
    act(() => result.current.stream('second', 'partial', false))
    act(() => result.current.advance())
    act(() => result.current.previous())
    act(() => {
      if (operation === 'clear') result.current.clear()
      else if (operation === 'restore') result.current.restore(['replacement'])
      else result.current.cut('replacement')
    })
    act(() => result.current.stream('second', 'late update', true))
    expect(result.current.pageCount).toBe(operation === 'clear' ? 0 : 1)
    expect(result.current.line).toBe(operation === 'clear' ? 'first complete' : 'replacement')
  })

  it('drains trailing acts on completion exactly once even while browsing an older page', () => {
    const play = vi.fn()
    const { result } = renderHook(() => useSpeech())
    act(() => result.current.say('first'))
    act(() => result.current.stream('second-stream', 'partial', false))
    act(() => result.current.advance())
    act(() => result.current.previous())
    act(() => result.current.act(play))
    act(() => result.current.stream('second-stream', 'finished', true))
    expect(play).toHaveBeenCalledOnce()
    act(() => result.current.stream('second-stream', 'finished again', true))
    expect(play).toHaveBeenCalledOnce()
  })
})
