#!/bin/bash
# SessionStart hook: put a maid "on shift".
# Reads the chosen persona's body (frontmatter stripped) from the plugin's own
# bundled `vendor/` dir (generated by build.ts from @claudecafe/maids) — self-
# contained, so it works from the marketplace cache with no external link, no env
# var, no repo path, and no `node` dependency (hooks run in a non-interactive
# shell that may not have node/bun on PATH).
#   CLAUDE_MAID  which maid is on shift (default: kurumi)
set -euo pipefail
cat > /dev/null   # drain the hook payload on stdin

MAID="${CLAUDE_MAID:-kurumi}"
CAST_DIR="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}/vendor"
FILE="$CAST_DIR/$MAID.md"

[ -f "$FILE" ] || exit 0   # persona not found -> stay in the default voice

echo "Adopt this persona for the entire session — it overrides the default assistant voice:"
echo
# Emit the body, stripping the leading YAML frontmatter (--- ... ---).
awk 'NR==1 && $0=="---"{f=1; next} f && $0=="---"{f=0; next} !f' "$FILE"
echo
echo "Respond in 台灣中文."
