#!/usr/bin/env bash
set -euo pipefail

# OpenCode loads TypeScript directly, so keep a checked-in copy of the
# host-neutral contracts in its package boundary. The canonical source remains
# packages/character-core; this copy is refreshed before checks and packing.
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOURCE="$ROOT/packages/character-core/src"
DEST="$ROOT/packages/opencode/src/character-core"

rm -rf "$DEST"
mkdir -p "$DEST"
for file in expression.ts persona.ts prompt.ts selection.ts index.ts; do
  cp "$SOURCE/$file" "$DEST/$file"
done
cat > "$DEST/README.md" <<'EOF'
This directory is generated by `scripts/build-opencode-core.sh`.

Edit `packages/character-core/src/` instead; run the build script before
checking or packing the OpenCode plugin so the published package carries the
same contracts without a workspace-only import.
EOF
